# Generated by Django 4.2.13 on 2026-06-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
